version: "3"
services:

  entry:
    build:
      context: .
      dockerfile: entry_point/Dockerfile
    networks:
      - 1sink_entry
      - 2sink_entry
      - 32sink_entry
      - entry_2ventilator
      - entry_1ventilator
      - entry_32ventilator
      - 2net
      - 32net
    environment:
      - VENT1_ENDPOINT=tcp://*:5570
      - VENT2_ENDPOINT=tcp://*:5571
      - VENT3_ENDPOINT=tcp://*:5572
      - ENDPOINT=tcp://*:5573

  1_ventilator:
    build:
      context: .
      dockerfile: 1_ventilator/Dockerfile
    depends_on:
      - entry
      - 1_middleware
      - 1_sink
      - 1_reducer
    networks:
      - entry_1ventilator
      - 1ventilator_1mapper
    environment:
      - MAPPERS=2
      - DATASET_DIR=NBA-shot-log
      - ENTRY_ENDPOINT=tcp://entry:5570
      - ENDPOINT=tcp://*:5580
      - MAPPERS_READY_ENDPOINT=tcp://*:5581

  2_ventilator:
    build:
      context: .
      dockerfile: 2_ventilator/Dockerfile
    depends_on:
      - entry
      - 2_middleware
      - 2_sink
      - 2_reducer
    networks:
      - 2net
    environment:
      - MAPPERS=2
      - DATASET_DIR=NBA-shot-log
      - ENTRY_ENDPOINT=tcp://entry:5571
      - ENDPOINT=tcp://*:5562
      - MAPPERS_READY_ENDPOINT=tcp://*:5563

  32_ventilator:
    build:
      context: .
      dockerfile: 32_ventilator/Dockerfile
    depends_on:
      - entry
      - 32_middleware
      - 32_sink
      - 32_reducer
    networks:
      - 32net
    environment:
      - MAPPERS=2
      - DATASET_DIR=NBA-shot-log
      - ENTRY_ENDPOINT=tcp://entry:5572
      - ENDPOINT=tcp://*:5590
      - MAPPERS_READY_ENDPOINT=tcp://*:5591

  1_mapper:
    build:
      context: .
      dockerfile: 1_mapper/Dockerfile
    depends_on:
      - entry
      - 1_middleware
      - 1_sink
      - 1_reducer
      - 1_ventilator
    networks:
      - 1mapper_1middleware
      - 1mapper_1reducerspawner
      - 1ventilator_1mapper
    environment:
      - MW_ENDPOINT=tcp://1_middleware:5584
      - KEYS_ENDPOINT=tcp://1_reducerspawner:5583
      - VENTILATOR_ENDPOINT=tcp://1_ventilator:5580
      - MAPPERS_READY_ENDPOINT=tcp://1_ventilator:5581

  2_mapper:
    build:
      context: .
      dockerfile: 2_mapper/Dockerfile
    depends_on:
      - entry
      - 2_middleware
      - 2_sink
      - 2_reducer
      - 2_ventilator
    networks:
      - 2net
    environment:
      - MW_ENDPOINT=tcp://2_middleware:5559
      - KEYS_ENDPOINT=tcp://2_reducerspawner:5560
      - VENTILATOR_ENDPOINT=tcp://2_ventilator:5562
      - MAPPERS_READY_ENDPOINT=tcp://2_ventilator:5563

  32_mapper:
    build:
      context: .
      dockerfile: 32_mapper/Dockerfile
    depends_on:
      - entry
      - 32_middleware
      - 32_sink
      - 32_reducer
      - 32_ventilator
    networks:
      - 32net
    environment:
      - MW_ENDPOINT=tcp://32_middleware:5592
      - KEYS_ENDPOINT=tcp://32_reducerspawner:5593
      - VENTILATOR_ENDPOINT=tcp://32_ventilator:5590
      - MAPPERS_READY_ENDPOINT=tcp://32_ventilator:5591

  1_middleware:
    build:
      context: .
      dockerfile: 1_middleware/Dockerfile
    depends_on:
      - entry
    networks:
      - 1mapper_1middleware
      - 1middleware_1reducer
    environment:
      - MAPPERS=2
      - REDUCERS=2
      - ENDPOINT=tcp://*:5584
      - REDUCER_READY_ENDPOINT=tcp://*:5585

  2_middleware:
    build:
      context: .
      dockerfile: 2_middleware/Dockerfile
    depends_on:
      - entry
    networks:
      - 2net
    environment:
      - MAPPERS=2
      - REDUCERS=2
      - ENDPOINT=tcp://*:5559
      - REDUCER_READY_ENDPOINT=tcp://*:5561

  32_middleware:
      build:
        context: .
        dockerfile: 32_middleware/Dockerfile
      depends_on:
        - entry
      networks:
        - 32net
      environment:
        - MAPPERS=2
        - REDUCERS=2
        - ENDPOINT=tcp://*:5592
        - REDUCER_READY_ENDPOINT=tcp://*:5594

  1_reducer:
      build:
        context: .
        dockerfile: 1_reducer/Dockerfile
      depends_on:
        - entry
        - 1_middleware
        - 1_sink
        - 1_reducerspawner
      networks:
        - 1middleware_1reducer
        - 1reducerspawner_1reducer
        - 1reducer_1sink
      environment:
        - MW_ENDPOINT=tcp://1_middleware:5584
        - REDUCER_MW_READY_ENDPOINT=tcp://1_middleware:5585
        - REDUCER_HANDLER_READY_ENDPOINT=tcp://1_reducerspawner:5586
        - SINK_ENDPOINT=tcp://1_sink:5587
        - KEYS_ENDPOINT=tcp://1_reducerspawner:5600

  1_reducerspawner:
    build:
      context: .
      dockerfile: 1_reducerspawner/Dockerfile
    depends_on:
      - entry
      - 1_middleware
      - 1_sink
    networks:
      - 1middleware_1reducerspawner
      - 1reducerspawner_1reducer
      - 1mapper_1reducerspawner
      - 1reducerspawner_1sink
    environment:
      - MAPPERS=2
      - REDUCERS=2
      - KEY_QUEUE_ENDPOINT=tcp://*:5583
      - KEYS_REDUCERS_ENDPOINT=tcp://*:5600
      - REDUCERS_READY_ENDPOINT=tcp://*:5586
      - SPAWNER_SINK_ENDPOINT=tcp://1_sink:5588

  2_reducer:
      build:
        context: .
        dockerfile: 2_reducer/Dockerfile
      depends_on:
        - entry
        - 2_middleware
        - 2_sink
        - 2_reducerspawner
      networks:
        - 2net
      environment:
        - MW_ENDPOINT=tcp://2_middleware:5559
        - REDUCER_MW_READY_ENDPOINT=tcp://2_middleware:5561
        - REDUCER_HANDLER_READY_ENDPOINT=tcp://2_reducerspawner:5564
        - SINK_ENDPOINT=tcp://2_sink:5568
        - KEYS_ENDPOINT=tcp://2_reducerspawner:5601

  2_reducerspawner:
    build:
      context: .
      dockerfile: 2_reducerspawner/Dockerfile
    depends_on:
      - entry
      - 2_middleware
      - 2_sink
    networks:
      - 2net
    environment:
      - MAPPERS=2
      - REDUCERS=2
      - KEY_QUEUE_ENDPOINT=tcp://*:5560
      - KEYS_REDUCERS_ENDPOINT=tcp://*:5601
      - REDUCERS_READY_ENDPOINT=tcp://*:5564
      - SPAWNER_SINK_ENDPOINT=tcp://2_sink:5569

  32_reducer:
      build:
        context: .
        dockerfile: 32_reducer/Dockerfile
      depends_on:
        - entry
        - 32_middleware
        - 32_sink
        - 32_reducerspawner
      networks:
        - 32net
      environment:
        - MW_ENDPOINT=tcp://32_middleware:5592
        - REDUCER_MW_READY_ENDPOINT=tcp://32_middleware:5594
        - REDUCER_HANDLER_READY_ENDPOINT=tcp://32_reducerspawner:5595
        - SINK_ENDPOINT=tcp://32_sink:5596
        - KEYS_ENDPOINT=tcp://32_reducerspawner:5602

  32_reducerspawner:
    build:
      context: .
      dockerfile: 32_reducerspawner/Dockerfile
    depends_on:
      - entry
      - 32_middleware
      - 32_sink
    networks:
      - 32net
    environment:
      - MAPPERS=2
      - REDUCERS=2
      - KEY_QUEUE_ENDPOINT=tcp://*:5593
      - KEYS_REDUCERS_ENDPOINT=tcp://*:5602
      - REDUCERS_READY_ENDPOINT=tcp://*:5595
      - SPAWNER_SINK_ENDPOINT=tcp://32_sink:5597

  1_sink:
    build:
      context: .
      dockerfile: 1_sink/Dockerfile
    depends_on:
      - entry
      - 1_middleware
    networks:
      - 1reducer_1sink
      - 1reducerspawner_1sink
      - 1sink_entry
    environment:
      - ENDPOINT=tcp://*:5587
      - REDUCER_SPAWNER_ENDPOINT=tcp://*:5588
      - COLLECTOR_ENDPOINT=tcp://entry:5573

  2_sink:
    build:
      context: .
      dockerfile: 2_sink/Dockerfile
    depends_on:
      - entry
      - 2_middleware
    networks:
      - 2net
    environment:
      - ENDPOINT=tcp://*:5568
      - REDUCER_SPAWNER_ENDPOINT=tcp://*:5569
      - COLLECTOR_ENDPOINT=tcp://entry:5573

  32_sink:
    build:
      context: .
      dockerfile: 32_sink/Dockerfile
    depends_on:
      - entry
      - 32_middleware
    networks:
      - 32net
    environment:
      - ENDPOINT=tcp://*:5596
      - REDUCER_SPAWNER_ENDPOINT=tcp://*:5597
      - COLLECTOR_ENDPOINT=tcp://entry:5573

networks:
  entry_1ventilator:
  1ventilator_1mapper:
  1mapper_1middleware:
  1middleware_1reducer:
  1reducer_1sink:
  1sink_entry:
  entry_2ventilator:
  #2ventilator_2mapper:
  #2mapper_2middleware:
  #2middleware_2reducer:
  #2reducer_2sink:
  2sink_entry:
  entry_32ventilator:
  #32ventilator_32mapper:
  #32mapper_32middleware:
  #32middleware_32reducer:
  #32reducer_32sink:
  32sink_entry:

  1middleware_1reducerspawner:
  1reducerspawner_1reducer:
  1mapper_1reducerspawner:
  1reducerspawner_1sink:

  #2middleware_2reducerspawner:
  #2reducerspawner_2reducer:
  #2mapper_2reducerspawner:
  #2reducerspawner_2sink:

  2net:
  32net:
  #32middleware_32reducerspawner:
  #32reducerspawner_32reducer:
  #32mapper_32reducerspawner:
  #32reducerspawner_32sink: