version: "3"
services:

  entry:
    build:
      context: .
      dockerfile: entry_point/Dockerfile
    networks:
      - 1net
      - 2net
      - 31net
      - 32net
    environment:
      - VENT1_ENDPOINT=tcp://*:5570
      - VENT2_ENDPOINT=tcp://*:5571
      - VENT3_ENDPOINT=tcp://*:5572
      - ENDPOINT=tcp://*:5573
      - DATASET_DIR=NBA-shot-log
      - DISPATCHER_READY_ENDPOINT=tcp://*:5700

  1_shotlogdispatcher:
    build:
      context: .
      dockerfile: 1_shotlogdispatcher/Dockerfile
    depends_on:
      - entry
      - 1_middleware
      - 1_sink
      - 1_reducer
    networks:
      - 1net
    environment:
      - MAPPERS=2
      - ENTRY_ENDPOINT=tcp://entry:5570
      - ENDPOINT=tcp://*:5580
      - MAPPERS_READY_ENDPOINT=tcp://*:5581
      - DISPATCHER_READY_ENDPOINT=tcp://entry:5700

  2_shotlogdispatcher:
    build:
      context: .
      dockerfile: 2_shotlogdispatcher/Dockerfile
    depends_on:
      - entry
      - 2_middleware
      - 2_sink
      - 2_reducer
    networks:
      - 2net
    environment:
      - MAPPERS=2
      - ENTRY_ENDPOINT=tcp://entry:5571
      - ENDPOINT=tcp://*:5562
      - MAPPERS_READY_ENDPOINT=tcp://*:5563
      - DISPATCHER_READY_ENDPOINT=tcp://entry:5700

  31_shotlogdispatcher:
    build:
      context: .
      dockerfile: 31_shotlogdispatcher/Dockerfile
    depends_on:
      - entry
      - 1_sink
      - 31_middleware
      - 31_sink
      - 31_reducer
    networks:
      - 31net
    environment:
      - MAPPERS=2
      - ENTRY_ENDPOINT=tcp://1_sink:5703
      - ENDPOINT=tcp://*:5701
      - MAPPERS_READY_ENDPOINT=tcp://*:5702
      - DISPATCHER_READY_ENDPOINT=tcp://1_sink:5704

  32_shotlogdispatcher:
    build:
      context: .
      dockerfile: 32_shotlogdispatcher/Dockerfile
    depends_on:
      - entry
      - 32_middleware
      - 32_sink
      - 32_reducer
    networks:
      - 32net
    environment:
      - MAPPERS=2
      - ENTRY_ENDPOINT=tcp://entry:5572
      - ENDPOINT=tcp://*:5590
      - MAPPERS_READY_ENDPOINT=tcp://*:5591
      - DISPATCHER_READY_ENDPOINT=tcp://entry:5700

  1_mapper:
    build:
      context: .
      dockerfile: 1_mapper/Dockerfile
    depends_on:
      - entry
      - 1_middleware
      - 1_sink
      - 1_reducer
      - 1_shotlogdispatcher
    networks:
      - 1net
    environment:
      - MW_ENDPOINT=tcp://1_middleware:5584
      - KEYS_ENDPOINT=tcp://1_reducerhandler:5583
      - VENTILATOR_ENDPOINT=tcp://1_shotlogdispatcher:5580
      - MAPPERS_READY_ENDPOINT=tcp://1_shotlogdispatcher:5581

  2_mapper:
    build:
      context: .
      dockerfile: 2_mapper/Dockerfile
    depends_on:
      - entry
      - 2_middleware
      - 2_sink
      - 2_reducer
      - 2_shotlogdispatcher
    networks:
      - 2net
    environment:
      - MW_ENDPOINT=tcp://2_middleware:5559
      - KEYS_ENDPOINT=tcp://2_reducerhandler:5560
      - VENTILATOR_ENDPOINT=tcp://2_shotlogdispatcher:5562
      - MAPPERS_READY_ENDPOINT=tcp://2_shotlogdispatcher:5563

  31_mapper:
    build:
      context: .
      dockerfile: 31_mapper/Dockerfile
    depends_on:
      - entry
      - 31_middleware
      - 31_sink
      - 31_reducer
      - 31_shotlogdispatcher
    networks:
      - 31net
    environment:
      - MW_ENDPOINT=tcp://31_middleware:5705
      - KEYS_ENDPOINT=tcp://31_reducerhandler:5709
      - VENTILATOR_ENDPOINT=tcp://31_shotlogdispatcher:5701
      - MAPPERS_READY_ENDPOINT=tcp://31_shotlogdispatcher:5702

  32_mapper:
    build:
      context: .
      dockerfile: 32_mapper/Dockerfile
    depends_on:
      - entry
      - 32_middleware
      - 32_sink
      - 32_reducer
      - 32_shotlogdispatcher
    networks:
      - 32net
    environment:
      - MW_ENDPOINT=tcp://32_middleware:5592
      - KEYS_ENDPOINT=tcp://32_reducerhandler:5593
      - VENTILATOR_ENDPOINT=tcp://32_shotlogdispatcher:5590
      - MAPPERS_READY_ENDPOINT=tcp://32_shotlogdispatcher:5591

  1_middleware:
    build:
      context: .
      dockerfile: 1_middleware/Dockerfile
    depends_on:
      - entry
    networks:
      - 1net
    environment:
      - MAPPERS=2
      - REDUCERS=2
      - ENDPOINT=tcp://*:5584
      - REDUCER_READY_ENDPOINT=tcp://*:5585

  2_middleware:
    build:
      context: .
      dockerfile: 2_middleware/Dockerfile
    depends_on:
      - entry
    networks:
      - 2net
    environment:
      - MAPPERS=2
      - REDUCERS=2
      - ENDPOINT=tcp://*:5559
      - REDUCER_READY_ENDPOINT=tcp://*:5561

  31_middleware:
    build:
      context: .
      dockerfile: 31_middleware/Dockerfile
    depends_on:
      - entry
      - 1_sink
    networks:
      - 31net
    environment:
      - MAPPERS=2
      - REDUCERS=2
      - ENDPOINT=tcp://*:5705
      - REDUCER_READY_ENDPOINT=tcp://*:5706

  32_middleware:
    build:
      context: .
      dockerfile: 32_middleware/Dockerfile
    depends_on:
      - entry
    networks:
      - 32net
    environment:
      - MAPPERS=2
      - REDUCERS=2
      - ENDPOINT=tcp://*:5592
      - REDUCER_READY_ENDPOINT=tcp://*:5594

  1_reducer:
    build:
      context: .
      dockerfile: 1_reducer/Dockerfile
    depends_on:
      - entry
      - 1_middleware
      - 1_sink
      - 1_reducerhandler
    networks:
        - 1net
    environment:
      - MW_ENDPOINT=tcp://1_middleware:5584
      - REDUCER_MW_READY_ENDPOINT=tcp://1_middleware:5585
      - REDUCER_HANDLER_READY_ENDPOINT=tcp://1_reducerhandler:5586
      - SINK_ENDPOINT=tcp://1_sink:5587
      - KEYS_ENDPOINT=tcp://1_reducerhandler:5600

  1_reducerhandler:
    build:
      context: .
      dockerfile: 1_reducerhandler/Dockerfile
    depends_on:
      - entry
      - 1_middleware
      - 1_sink
    networks:
      - 1net
    environment:
      - MAPPERS=2
      - REDUCERS=2
      - KEY_QUEUE_ENDPOINT=tcp://*:5583
      - KEYS_REDUCERS_ENDPOINT=tcp://*:5600
      - REDUCERS_READY_ENDPOINT=tcp://*:5586
      - SPAWNER_SINK_ENDPOINT=tcp://1_sink:5588

  2_reducer:
    build:
      context: .
      dockerfile: 2_reducer/Dockerfile
    depends_on:
      - entry
      - 2_middleware
      - 2_sink
      - 2_reducerhandler
    networks:
      - 2net
    environment:
      - MW_ENDPOINT=tcp://2_middleware:5559
      - REDUCER_MW_READY_ENDPOINT=tcp://2_middleware:5561
      - REDUCER_HANDLER_READY_ENDPOINT=tcp://2_reducerhandler:5564
      - SINK_ENDPOINT=tcp://2_sink:5568
      - KEYS_ENDPOINT=tcp://2_reducerhandler:5601

  2_reducerhandler:
    build:
      context: .
      dockerfile: 2_reducerhandler/Dockerfile
    depends_on:
      - entry
      - 2_middleware
      - 2_sink
    networks:
      - 2net
    environment:
      - MAPPERS=2
      - REDUCERS=2
      - KEY_QUEUE_ENDPOINT=tcp://*:5560
      - KEYS_REDUCERS_ENDPOINT=tcp://*:5601
      - REDUCERS_READY_ENDPOINT=tcp://*:5564
      - SPAWNER_SINK_ENDPOINT=tcp://2_sink:5569

  31_reducer:
    build:
      context: .
      dockerfile: 31_reducer/Dockerfile
    depends_on:
      - entry
      - 31_middleware
      - 31_sink
      - 31_reducerhandler
    networks:
        - 31net
    environment:
      - MW_ENDPOINT=tcp://31_middleware:5705
      - REDUCER_MW_READY_ENDPOINT=tcp://31_middleware:5706
      - REDUCER_HANDLER_READY_ENDPOINT=tcp://31_reducerhandler:5708
      - SINK_ENDPOINT=tcp://31_sink:5711
      - KEYS_ENDPOINT=tcp://31_reducerhandler:5710

  31_reducerhandler:
    build:
      context: .
      dockerfile: 31_reducerhandler/Dockerfile
    depends_on:
      - entry
      - 31_middleware
      - 31_sink
    networks:
      - 31net
    environment:
      - MAPPERS=2
      - REDUCERS=2
      - KEY_QUEUE_ENDPOINT=tcp://*:5709
      - KEYS_REDUCERS_ENDPOINT=tcp://*:5710
      - REDUCERS_READY_ENDPOINT=tcp://*:5708
      - SPAWNER_SINK_ENDPOINT=tcp://31_sink:5712

  32_reducer:
    build:
      context: .
      dockerfile: 32_reducer/Dockerfile
    depends_on:
      - entry
      - 32_middleware
      - 32_sink
      - 32_reducerhandler
    networks:
      - 32net
    environment:
      - MW_ENDPOINT=tcp://32_middleware:5592
      - REDUCER_MW_READY_ENDPOINT=tcp://32_middleware:5594
      - REDUCER_HANDLER_READY_ENDPOINT=tcp://32_reducerhandler:5595
      - SINK_ENDPOINT=tcp://32_sink:5596
      - KEYS_ENDPOINT=tcp://32_reducerhandler:5602

  32_reducerhandler:
    build:
      context: .
      dockerfile: 32_reducerhandler/Dockerfile
    depends_on:
      - entry
      - 32_middleware
      - 32_sink
    networks:
      - 32net
    environment:
      - MAPPERS=2
      - REDUCERS=2
      - KEY_QUEUE_ENDPOINT=tcp://*:5593
      - KEYS_REDUCERS_ENDPOINT=tcp://*:5602
      - REDUCERS_READY_ENDPOINT=tcp://*:5595
      - SPAWNER_SINK_ENDPOINT=tcp://32_sink:5597

  1_sink:
    build:
      context: .
      dockerfile: 1_sink/Dockerfile
    depends_on:
      - entry
      - 1_middleware
    networks:
      - 1net
      - 31net
    environment:
      - ENDPOINT=tcp://*:5587
      - REDUCER_SPAWNER_ENDPOINT=tcp://*:5588
      - COLLECTOR_ENDPOINT=tcp://entry:5573

      - VENTILATOR_ENDPOINT=tcp://*:5703
      - DISPATCHER_READY_ENDPOINT=tcp://*:5704

  2_sink:
    build:
      context: .
      dockerfile: 2_sink/Dockerfile
    depends_on:
      - entry
      - 2_middleware
    networks:
      - 2net
    environment:
      - ENDPOINT=tcp://*:5568
      - REDUCER_SPAWNER_ENDPOINT=tcp://*:5569
      - COLLECTOR_ENDPOINT=tcp://entry:5573

  31_sink:
    build:
      context: .
      dockerfile: 31_sink/Dockerfile
    depends_on:
      - entry
      - 31_middleware
    networks:
      - 31net
    environment:
      - ENDPOINT=tcp://*:5711
      - REDUCER_SPAWNER_ENDPOINT=tcp://*:5712
      - COLLECTOR_ENDPOINT=tcp://entry:5573

  32_sink:
    build:
      context: .
      dockerfile: 32_sink/Dockerfile
    depends_on:
      - entry
      - 32_middleware
    networks:
      - 32net
    environment:
      - ENDPOINT=tcp://*:5596
      - REDUCER_SPAWNER_ENDPOINT=tcp://*:5597
      - COLLECTOR_ENDPOINT=tcp://entry:5573

networks:
  1net:
  2net:
  31net:
  32net: